In [1]:
import pandas as pd
import numpy as np
import matplotlib.style as style
import matplotlib.pyplot as plt 

In [3]:
glass = pd.read_csv("./glass.csv", skipinitialspace= True)
glass.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [4]:
glass.dtypes

RI      float64
Na      float64
Mg      float64
Al      float64
Si      float64
K       float64
Ca      float64
Ba      float64
Fe      float64
Type      int64
dtype: object

In [6]:
glass.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [8]:
glass.duplicated().sum()

1

In [10]:
glass.drop_duplicates(inplace= True)
glass.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [12]:
# Machine learning algorithm to make predictions
# random forest algorithm
x = glass[["RI", "Na", "Mg", "Al", "Si", "K", "Ca", "Ba", "Fe"]]
y = glass[["Type"]]


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 0)

from sklearn.ensemble import RandomForestClassifier
rnd = RandomForestClassifier(n_estimators= 20, random_state= 0)


rnd.fit(X_train, y_train)
y_pred = rnd.predict(X_test) 
y_pred

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred)) 

C:\Users\DELL LATITUDE E5270\AppData\Local\Temp\ipykernel_8612\605378882.py:14: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rnd.fit(X_train, y_train)


[[ 7  2  0  0  0  0]
 [ 3 15  0  0  0  0]
 [ 3  1  2  0  0  0]
 [ 0  1  0  1  0  0]
 [ 0  1  0  0  1  0]
 [ 0  1  0  0  0  5]]
              precision    recall  f1-score   support

           1       0.54      0.78      0.64         9
           2       0.71      0.83      0.77        18
           3       1.00      0.33      0.50         6
           5       1.00      0.50      0.67         2
           6       1.00      0.50      0.67         2
           7       1.00      0.83      0.91         6

    accuracy                           0.72        43
   macro avg       0.88      0.63      0.69        43
weighted avg       0.78      0.72      0.71        43

0.7209302325581395


In [13]:
y_pred

array([7, 1, 2, 5, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 7, 2, 2, 3, 1, 6, 7,
       7, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 3, 2, 7, 2, 2, 2],
      dtype=int64)

In [14]:
print(accuracy_score(y_test, y_pred))

0.7209302325581395
